/*
 * extracted.c — generated by #extract_to_c (Pass B walker).
 * Runtime: egpt_num (FRAQTL/fat/crates/egpt_num).
 */

#include <stdio.h>
#include <stdlib.h>
#include "egpt_num.h"

#define BUDGET 16

/* Realizer for Real.exp via monotone Taylor partial sums.
 * S_N(x) = Σ_{k=0..N} x^k / k!  — converges to exp(x) from below for x ≥ 0.
 * Caller owns the returned handle; free with egpt_free.
 */
static EgptNumber *exp_partial_sum(const EgptNumber *x, int budget) {
    EgptNumber *s = egpt_from_i64(1);    /* S_0 = 1 */
    EgptNumber *term = egpt_from_i64(1); /* x^0 / 0! = 1 */
    for (int k = 1; k <= budget; ++k) {
        EgptNumber *k_num = egpt_from_i64((int64_t)k);
        EgptNumber *tx    = egpt_mul(term, x);
        EgptNumber *new_term = egpt_div(tx, k_num);
        egpt_free(term); egpt_free(k_num); egpt_free(tx);
        term = new_term;
        EgptNumber *new_s = egpt_add(s, term);
        egpt_free(s);
        s = new_s;
    }
    egpt_free(term);
    return s;
}

/* Realizer for Real.sqrt via Newton's method on exact rationals.
 *   y_{n+1} = (y_n + x/y_n) / 2,  y_0 = x + 1   (y_0 > sqrt(x) for x ≥ 0).
 * Newton converges monotonically from above; all iterates are upper bounds
 * on the true sqrt. Sound for inequalities of the form `k < sqrt(x)` when
 * k < sqrt(x) strictly; unsound tight upper-bound inequalities without
 * additional budget reasoning — see PLAN.md §Pass C caveats.
 */
static EgptNumber *sqrt_partial_newton(const EgptNumber *x, int budget) {
    EgptNumber *two = egpt_from_i64(2);
    EgptNumber *one = egpt_from_i64(1);
    EgptNumber *y = egpt_add(x, one);  /* y_0 = x + 1 */
    egpt_free(one);
    for (int i = 0; i < budget; ++i) {
        EgptNumber *xy = egpt_div(x, y);
        EgptNumber *sum = egpt_add(y, xy);
        EgptNumber *new_y = egpt_div(sum, two);
        egpt_free(xy); egpt_free(sum); egpt_free(y);
        y = new_y;
    }
    egpt_free(two);
    return y;
}

/* Target theorem: Extraction.forall_fin_three_val_lt_three */
int main(void) {
    int result = 0;
    result = 1;
    for (int __i = 0; __i < 3; ++__i) {
        EgptNumber *__witness = egpt_from_i64((int64_t)__i);
        int __hold = (egpt_cmp(__witness, egpt_from_i64(3)) == -1);
        egpt_free(__witness);
        if (!__hold) { result = 0; break; }
    }
    printf("%s\n", result ? "true" : "false");
    return result ? 0 : 1;
}
