import Archive.Core
import Archive.Complexity.Core
import Archive.Complexity.SetRFL
import Archive.Complexity.Decomposition
import Archive.Complexity.TableauFromCNF
import Archive.NumberTheory.Core
import Archive.NumberTheory.Filter
import Archive.Constraints
import Archive.Entropy.Common

open EGPT EGPT.Complexity EGPT.NumberTheory.Core EGPT.Constraints
open EGPT.Entropy.Common EGPT.NumberTheory.Filter

namespace EGPT.Complexity.UTM

/-! ## Load-bearing Chain 1 declarations

The definitions and theorems in this first section are imported by
`PPNP.lean` and form part of the P=NP proof chain (Chain 1).
They include the ReadHead / timeComplexity model, the RECT/IRECT bridge,
the polarity-encoded literal address machinery, the NDM address walk,
the NDM entropy walk, and the NDM circuit evaluation layer.
-/

/-!
# The EGPT Computation Model

This file contains:
1. **Sequential Tape Reading** — the ReadHead model proving time = tape length
2. **RECT/IRECT Connection** — time = information = program complexity
3. **Deterministic Breadth Construction** — clause-by-clause filtering, survivor programs
4. **NDM Particle Transport** — memoryless Markov state transitions, constrained paths
5. **PProgram = NP Verifier** — survivor programs as polynomial witness verifiers

## Why Memory Access Is Not Free

The standard RAM model assumes O(1) memory access: reading any cell costs one
step regardless of its position. This is a cost-accounting abstraction that does
not hold in physical reality. To access bit n on a tape, a read head must
traverse n positions. The standard model hides this traversal cost.

The standard Turing Machine model charges for head movement (one step per cell),
but still allows the machine to revisit cells and loop — so a tape of length L
can drive 2^L or more steps of computation, because the TM can use the tape as
rewritable working memory.

EGPT's computation model is different:

1. **The tape is read-only.** A `ComputerProgram` is a `List Bool` — a sequence
   of binary instructions generated by an `IIDParticleSource`. Each bit is one
   independent choice from a fair coin (or biased source). The tape records the
   history of a random walk. You read it; you don't rewrite it.

2. **Each bit costs one step.** Reading one `ComputerInstruction` (= `Bool`) from
   the tape is one computational step. The tape is processed sequentially, head
   to tail. There are no jumps, no loops, no revisits.

3. **The tape IS maximally compressed.** For a `ParticlePath`, every bit is `true`
   (`PathCompress_AllTrue`). There is zero redundancy. Every bit carries
   information. This is Shannon's optimal code for an IID source — and
   `IIDParticleSource` IS Shannon's source.

4. **Therefore: time complexity = tape length = information content.** The LFTA
   proves primes are perfect Shannon coders (`log(n) = Σ v_p(n) · log(p)`).
   Rota's theorem proves log is the unique entropy function. RECT/IRECT proves
   information content = program complexity. Sequential reading proves
   program complexity = time complexity. The chain is closed.

## The Read Head Model

We formalize this as a `ReadHead` that processes a tape bit by bit. At each
step, the head reads one bit and advances. The number of steps taken is
provably equal to the tape length. No loops, no revisits, no free jumps.

This is intentionally minimal: the "computation" IS the reading. The tape
(generated by the IID source, compressed into a ParticlePath, encoding the
CNF's constraint structure) already contains the answer. The read head's job
is to process it, and the cost of processing is the tape length.
-/

/--
The state of a sequential tape reader at any point during execution.
`remaining` is the unread portion of the tape; `steps` counts how many
bits have been read so far.
-/
structure ReadHead where
  remaining : ComputerTape
  steps     : ℕ

/--
Initialize the read head at the beginning of a tape. Zero steps taken.
-/
def ReadHead.init (tape : ComputerTape) : ReadHead :=
  { remaining := tape, steps := 0 }

/--
One step of execution: read one bit from the tape head, advance, increment
the step counter. Returns `none` if the tape is exhausted.
-/
def ReadHead.step (head : ReadHead) : Option (Bool × ReadHead) :=
  match head.remaining with
  | [] => none
  | bit :: rest => some (bit, { remaining := rest, steps := head.steps + 1 })

/--
Run the read head to completion: process every bit on the tape sequentially.
Returns the final state (empty tape, all steps counted).
-/
def ReadHead.run : ReadHead → ReadHead
  | { remaining := [], steps := s } => { remaining := [], steps := s }
  | { remaining := _ :: rest, steps := s } =>
      ReadHead.run { remaining := rest, steps := s + 1 }
termination_by head => head.remaining.length

/--
**The time complexity of a program in the EGPT model**: the number of
sequential read steps required to process the entire tape.

This is defined as the step count after running the read head to completion.
-/
def timeComplexity (prog : ComputerProgram) : ℕ :=
  (ReadHead.init prog |>.run).steps

/-!
### Core Theorems: Time Complexity = Tape Length
-/

/--
After running the read head on a tape, the remaining tape is empty.
Every bit has been processed.
-/
theorem ReadHead.run_exhausts (head : ReadHead) :
    (head.run).remaining = [] := by
  induction head using ReadHead.run.induct with
  | case1 s => simp [ReadHead.run]
  | case2 bit rest s ih => simp [ReadHead.run]; exact ih

/--
The step count after running equals the initial steps plus the tape length.
This is the key lemma: every bit contributes exactly one step.
-/
theorem ReadHead.run_steps (head : ReadHead) :
    (head.run).steps = head.steps + head.remaining.length := by
  induction head using ReadHead.run.induct with
  | case1 s => simp [ReadHead.run]
  | case2 bit rest s ih =>
    simp [ReadHead.run]
    rw [ih]
    simp [List.length_cons]
    omega

/--
**Time complexity equals tape length.**

For any `ComputerProgram`, the EGPT time complexity (number of sequential
read operations) is exactly the tape length. Each bit costs one step.
No free memory access. No loops. No revisits.

This is the formal statement that in the EGPT computation model,
**program complexity = time complexity = information content**.

Combined with:
- RECT/IRECT: information content = program complexity
- Shannon SCT: optimal code length = entropy for IID source
- Rota: log is the unique entropy function
- LFTA: primes are perfect Shannon coders

The chain is: time complexity = tape length = information content = entropy.
-/
theorem timeComplexity_eq_length (prog : ComputerProgram) :
    timeComplexity prog = prog.length := by
  simp [timeComplexity, ReadHead.init, ReadHead.run_steps]

/--
Time complexity of a `ParticlePath` program equals its `toNat` value.
Since `toNat p = p.val.length`, this connects the time complexity to the
natural number the path represents.
-/
theorem timeComplexity_eq_toNat (p : ParticlePath) :
    timeComplexity p.val = toNat p := by
  rw [timeComplexity_eq_length]
  rfl

/--
Time complexity is additive under program composition.
Concatenating two programs costs the sum of their individual costs.
This reflects that sequential reading of `p ++ q` reads `p` then `q`.
-/
theorem timeComplexity_append (p q : ComputerProgram) :
    timeComplexity (List.append p q) = timeComplexity p + timeComplexity q := by
  simp [timeComplexity_eq_length]

/--
Time complexity of the empty program is zero.
-/
@[simp] theorem timeComplexity_nil : timeComplexity ([] : ComputerProgram) = 0 := by
  simp [timeComplexity_eq_length]

/--
Time complexity of a single instruction is one.
-/
@[simp] theorem timeComplexity_singleton (b : Bool) :
    timeComplexity [b] = 1 := by
  simp [timeComplexity_eq_length]

/-!
### Connection to RECT/IRECT: Time = Information

The EGPT equivalence cycle closes here. We show that time complexity
(sequential read steps) coincides with information content (IRECT) and
program complexity (RECT). The three quantities are the same number.
-/

/--
**The EGPT Equivalence: Time = Information = Program Complexity.**

For any `ComputationalDescription` (= `PathProgram`), the time complexity
of its tape equals its program complexity, which equals its information
content (by IRECT). All three are the same natural number.
-/
theorem time_eq_information_eq_complexity (prog : ComputationalDescription) :
    timeComplexity prog.tape = prog.complexity ∧
    (prog.complexity : ℝ) = IRECT_Program_to_Entropy prog := by
  constructor
  · simp [timeComplexity_eq_length, PathProgram.complexity]
  · simp [IRECT_Program_to_Entropy, PathProgram.complexity]

/--
**Corollary: For any information content L, the program that realizes it
has time complexity L.** There is no gap between information and time.
-/
theorem time_complexity_of_rect_program (L : ℕ) :
    ∃ (prog : ComputationalDescription),
      timeComplexity prog.tape = L ∧
      prog.complexity = L ∧
      IRECT_Program_to_Entropy prog = (L : ℝ) := by
  rcases IRECT_RECT_inverse_for_integer_complexity L with ⟨prog, h_entropy, h_complexity⟩
  exact ⟨prog, by rw [timeComplexity_eq_length, ← h_complexity]; rfl,
         h_complexity, h_entropy⟩

/-!
### Why O(1) Memory Access Is Wrong

In the standard RAM model, accessing memory cell n costs O(1) regardless of n.
This means a program of length L can "jump" to any of 2^L addressable cells
for free, enabling unbounded computation per bit of input.

In the EGPT model, there are no jumps. The tape is read sequentially. To
access the n-th bit, you must read bits 1 through n. The cost of reaching
position n is n, not 1.

This is not an arbitrary choice — it follows from the physical model:
- The tape is a particle path (a random walk history)
- Each bit is one step of the walk
- You cannot "skip ahead" in a walk — each step depends on the previous position
- The walk IS the computation, and each step costs one unit of time

The consequence: a program of length L processes exactly L bits of information
in exactly L time steps. There is no mechanism to amplify L bits into 2^L
steps of work, because there are no loops or revisits.
-/

/-! ## Supporting declarations (Debate Exchanges 17–18)

The definitions below — particle state evolution, non-deterministic machine
runner (`NDTM_A_run`), deterministic breadth construction
(`deterministicBreadthRun`, `breadthStep`, `BreadthState`, etc.), survivor
programs (`survivorPrograms`, `composeSurvivorPrograms`), and the
`ConstrainedSystem` / `DMachine_CS_verify` layer — are NOT directly
referenced by `PPNP.lean`. They remain here as foundational
context from the adversarial debate (Exchanges 17–18) and underpin the
address-space and entropy walk layers that ARE in the proof chain.
-/

/-!
==================================================================
# NDM Particle Transport Model (Exchange 17)

The particle state evolution, non-deterministic machine runner,
deterministic breadth construction, and survivor program extraction.

These definitions were consolidated from Physics.lean into the
computation model as part of the Exchange 17 NDM particle transport
formalization. The key insight: circuit I/O constraints ARE CanonicalCNF,
and the walk operates in address space (linear), not solution space
(exponential). See `18.313x/17_NDM_Particle_Transport.md`.
==================================================================
-/

/--
The state of a single particle in the SAT model.
Its 'law' is the probability of it being 'true' in the next state.
-/
structure ParticleState_SAT where
  value : Bool
  law : ParticleHistoryPMF

/--
`advance_state` computes the next system state by flipping a biased coin for each particle.
This is one step in the parallel Markov process.
-/
noncomputable def advance_state {k : ℕ} (current_states : Vector ParticleState_SAT k) (seed : ℕ) : Vector ParticleState_SAT k :=
  Vector.ofFn (fun i : Fin k =>
    let particle := current_states.get i
    let source := toBiasedSource particle.law (seed + i.val)
    let next_value := source.stream 0
    { particle with value := next_value }
  )

/--
`get_system_state_vector` extracts the boolean vector from particle states.
-/
def get_system_state_vector {k : ℕ} (states : Vector ParticleState_SAT k) : Vector Bool k :=
  states.map (fun p => p.value)

/--
**Computes a Potential Next State via a Memoryless Random Walk.**

This is the core state transition function of the EGPT physical model.
The function is memoryless: the next state candidate depends *only* on the
`current_state` and the `seed` for randomness, not on any prior history.
-/
noncomputable def potential_next_state {k : ℕ} (current_state : Vector Bool k) (seed : ℕ) : Vector Bool k :=
  let particle_states := Vector.ofFn (fun i => {
    value := current_state.get i,
    law   := EGPT.NumberTheory.Core.fromRat 1
  })
  let next_particle_states := advance_state particle_states seed
  get_system_state_vector next_particle_states

/--
**The EGPT Non-deterministic Machine (`NDTM_A`) Runner.**

Models computation as a physical process: a "computation particle" attempting
a random walk through a state space constrained by physical laws (CNF).

- **The Machine's "Program":** The `constraints` (`SyntacticCNF_EGPT k`) are the
  program. They define the physical laws of the computational universe.
- **Non-determinism:** The `seed` provides randomness. Different seeds lead to
  different computational paths. The problem is "accepted" if *any* seed finds
  a valid path.
- **Execution:** Random walk with rejection sampling. At each time step, generate
  a candidate next state. If it obeys the constraints, extend the path.

The output is `some path` if a valid computational history of `time_limit`
steps is found, and `none` otherwise.
-/
noncomputable def NDTM_A_run {k : ℕ} (constraints : SyntacticCNF_EGPT k) (time_limit : ℕ) (seed : ℕ) : Option (List (Vector Bool k)) :=
  let satisfying_states := (Finset.univ : Finset (Vector Bool k)).filter (fun v => evalCNF constraints v)
  let initial_state_opt := satisfying_states.toList.head?
  match initial_state_opt with
  | none => none
  | some initial_state =>
    let rec loop (t : ℕ) (current_path : List (Vector Bool k)) (current_seed : ℕ) : Option (List (Vector Bool k)) :=
      let current_state := current_path.head!
      if t >= time_limit then
        some (current_path.reverse)
      else
        let next_candidate := potential_next_state current_state current_seed
        if evalCNF constraints next_candidate then
          let new_path := next_candidate :: current_path
          loop (t + 1) new_path (current_seed + 1)
        else
          loop (t + 1) current_path (current_seed + 1)
    termination_by time_limit - t
    loop 0 [initial_state] seed

/--
**Creates a CNF formula that is uniquely satisfied by the given state vector `v`.**
The formula is a conjunction of `k` unit clauses, where the `i`-th clause fixes
the `i`-th variable to its value in `v`. For example, for `v = [true, false]`,
the CNF is `(x₀) ∧ (¬x₁)`.
-/
def cnf_for_specific_assignment {k : ℕ} (v : Vector Bool k) : SyntacticCNF_EGPT k :=
  List.ofFn (fun i : Fin k =>
    [{ particle_idx := i, polarity := v.get i }]
  )

-- A Constrained System is defined by a single set of laws.
abbrev ConstrainedSystem (k : ℕ) := SyntacticCNF_EGPT k

-- The verifier checks that EVERY state in the path obeys the laws.
def DMachine_CS_verify {k : ℕ} (sys : ConstrainedSystem k) (path_cert : List (Vector Bool k)) : Bool :=
  ¬path_cert.isEmpty ∧ path_cert.all (fun state => evalCNF sys state)

theorem constrainedSystem_equiv_SAT {k : ℕ} (sys : ConstrainedSystem k) :
  (∃ path : List (Vector Bool k), DMachine_CS_verify sys path = true) ↔
  (∃ assignment : Vector Bool k, evalCNF sys assignment = true) :=
by
  constructor
  · intro h_path_exists
    rcases h_path_exists with ⟨path, h_path_valid⟩
    simp only [DMachine_CS_verify] at h_path_valid
    have h_inner : ¬path.isEmpty ∧ path.all (fun state => evalCNF sys state) := by
      exact decide_eq_true_iff.mp h_path_valid
    have h_path_nonempty : ¬path.isEmpty := h_inner.1
    have h_all_states_valid : path.all (fun state => evalCNF sys state) := h_inner.2
    have h_ne_nil : path ≠ [] := by
      intro h_eq_nil
      rw [h_eq_nil] at h_path_nonempty
      simp at h_path_nonempty
    cases path with
    | nil => contradiction
    | cons head tail =>
        use head
        simp [List.all_cons] at h_all_states_valid
        exact h_all_states_valid.left
  · intro h_assignment_exists
    rcases h_assignment_exists with ⟨assignment, h_assignment_valid⟩
    use [assignment]
    simp only [DMachine_CS_verify, List.isEmpty_cons, List.all_cons, List.all_nil, Bool.not_false]
    simp [h_assignment_valid]

/-!
### Theorem: Underlying State Evolution is Memoryless (A Markov Process)

The state transition function used by the NDM is Markovian. The generation
of the *next candidate state* depends **only on the most recent state**
and the current seed. It has no dependency on prior history.
-/
theorem underlying_state_evolution_is_memoryless {k : ℕ} :
    ∀ (current_state : Vector Bool k) (current_seed : ℕ),
      (
        let particle_states := Vector.ofFn (fun i => { value := current_state.get i, law := EGPT.NumberTheory.Core.fromRat 1})
        get_system_state_vector (advance_state particle_states current_seed)
      )
      = potential_next_state current_state current_seed :=
by
  intro current_state current_seed
  simp [potential_next_state]

/-!
==================================================================
# Deterministic Breadth Construction

CNF-initialized deterministic breadth constructor:
- Initial state is the CNF program itself (no witness argument).
- Survivors are evolved clause-by-clause in canonical list order.
- Terminal survivors are exactly the satisfying assignments.
==================================================================
-/

/-- CNF magnitude used as a deterministic constructor time-limit parameter. -/
def CNFMagnitude {k : ℕ} (cnf : SyntacticCNF_EGPT k) : ℕ :=
  (encodeCNF cnf).length

/-- Deterministic breadth state over ordered CNF constraints. -/
structure BreadthState (k : ℕ) where
  cnf : SyntacticCNF_EGPT k
  step : ℕ
  survivors : Finset (Vector Bool k)

/-- Deterministic clause-filter step on current survivors. -/
def breadthStep {k : ℕ} (clause : Clause_EGPT k) (survivors : Finset (Vector Bool k)) :
    Finset (Vector Bool k) :=
  survivors.filter (fun v => evalClause clause v)

/-- CNF-initialized breadth state starts with all states as candidates. -/
def initBreadthState {k : ℕ} (cnf : SyntacticCNF_EGPT k) : BreadthState k := {
  cnf := cnf
  step := 0
  survivors := (Finset.univ : Finset (Vector Bool k))
}

/-- Single deterministic transition by consuming the next ordered clause. -/
def breadthAdvance {k : ℕ} (st : BreadthState k) : BreadthState k :=
  match st.cnf.drop st.step with
  | [] => st
  | clause :: _ =>
      { st with
        step := st.step + 1
        survivors := breadthStep clause st.survivors }

/-- Recursive deterministic breadth run from an initial survivor set. -/
def breadthRunFrom {k : ℕ} (survivors : Finset (Vector Bool k)) : SyntacticCNF_EGPT k → Finset (Vector Bool k)
  | [] => survivors
  | clause :: rest => breadthRunFrom (breadthStep clause survivors) rest

/-- Deterministic breadth constructor run in canonical CNF list order. -/
def deterministicBreadthRun {k : ℕ} (cnf : SyntacticCNF_EGPT k) : Finset (Vector Bool k) :=
  breadthRunFrom (Finset.univ : Finset (Vector Bool k)) cnf

/-- Deterministic breadth terminal state after exactly `cnf.length` transitions. -/
def deterministicBreadthFinalState {k : ℕ} (cnf : SyntacticCNF_EGPT k) : BreadthState k := {
  cnf := cnf
  step := cnf.length
  survivors := deterministicBreadthRun cnf
}

/-- Constructor cost model: one full variable sweep per clause row. -/
def deterministicBreadthCost {k : ℕ} (cnf : SyntacticCNF_EGPT k) : ℕ :=
  cnf.length * k

/-- The breadth constructor step-count is bounded by CNF magnitude. -/
lemma deterministicBreadth_steps_le_magnitude {k : ℕ} (cnf : SyntacticCNF_EGPT k) :
    cnf.length ≤ CNFMagnitude cnf := by
  simpa [CNFMagnitude] using (cnf_length_le_encoded_length cnf)

/-- Deterministic breadth transition-cost bound by encoded-size square. -/
theorem deterministicBreadth_cost_le_nSquared {k : ℕ} (cnf : SyntacticCNF_EGPT k) :
    deterministicBreadthCost cnf ≤ CNFMagnitude cnf * CNFMagnitude cnf := by
  unfold deterministicBreadthCost CNFMagnitude
  apply Nat.mul_le_mul
  · exact cnf_length_le_encoded_length cnf
  · exact encodeCNF_size_ge_k k cnf

/-- A survivor in one step iff it was in the prior set and satisfies that clause. -/
@[simp] lemma mem_breadthStep_iff {k : ℕ} (clause : Clause_EGPT k) (survivors : Finset (Vector Bool k))
    (v : Vector Bool k) :
    v ∈ breadthStep clause survivors ↔ v ∈ survivors ∧ evalClause clause v = true := by
  simp [breadthStep]

/--
Prefix invariant:
membership in `breadthRunFrom survivors clauses` is equivalent to
membership in the initial survivor set and truth of every processed clause.
-/
lemma mem_breadthRunFrom_iff {k : ℕ} (survivors : Finset (Vector Bool k))
    (clauses : SyntacticCNF_EGPT k) (v : Vector Bool k) :
    v ∈ breadthRunFrom survivors clauses ↔
      v ∈ survivors ∧ clauses.all (fun clause => evalClause clause v) = true := by
  induction clauses generalizing survivors with
  | nil =>
      simp [breadthRunFrom]
  | cons clause rest ih =>
      simp [breadthRunFrom, ih, and_assoc, Bool.and_eq_true]

/-- Terminal survivors are exactly the satisfying assignments of the CNF. -/
theorem mem_deterministicBreadthRun_iff_evalCNF {k : ℕ} (cnf : SyntacticCNF_EGPT k) (v : Vector Bool k) :
    v ∈ deterministicBreadthRun cnf ↔ evalCNF cnf v = true := by
  simpa [deterministicBreadthRun, evalCNF] using
    (mem_breadthRunFrom_iff (survivors := (Finset.univ : Finset (Vector Bool k))) (clauses := cnf) (v := v))

/--
`ConstructedSolutionSet` is the CNF-only constructed set of satisfying endpoints:
the terminal survivor set of deterministic breadth construction.
-/
def ConstructedSolutionSet {k : ℕ} (cnf : SyntacticCNF_EGPT k) : Finset (Vector Bool k) :=
  deterministicBreadthRun cnf

/--
Verifier by constructed-set membership.
Returns true exactly when the candidate is in the CNF-constructed solution set.
-/
def verify_via_constructedSet {k : ℕ} (cnf : SyntacticCNF_EGPT k) (candidate : Vector Bool k) : Bool :=
  decide (candidate ∈ ConstructedSolutionSet cnf)

/--
Core verifier equivalence chain:
verifying by constructed-set membership is equivalent to `evalCNF`.
-/
theorem verify_via_constructedSet_iff_evalCNF {k : ℕ}
    (cnf : SyntacticCNF_EGPT k) (candidate : Vector Bool k) :
    verify_via_constructedSet cnf candidate = true ↔ evalCNF cnf candidate = true := by
  unfold verify_via_constructedSet ConstructedSolutionSet
  simpa [decide_eq_true_eq] using (mem_deterministicBreadthRun_iff_evalCNF (cnf := cnf) (v := candidate))

/-- Constructor success iff CNF semantic set is nonempty. -/
theorem deterministicBreadthRun_nonempty_iff_allSatisfyingAssignments_nonempty {k : ℕ}
    (cnf : SyntacticCNF_EGPT k) :
    (deterministicBreadthRun cnf).Nonempty ↔ (EGPT.Complexity.SetRFL.AllSatisfyingAssignments cnf).Nonempty := by
  constructor
  · rintro ⟨v, hv⟩
    exact ⟨v, (mem_deterministicBreadthRun_iff_evalCNF cnf v).1 hv⟩
  · rintro ⟨v, hv⟩
    exact ⟨v, (mem_deterministicBreadthRun_iff_evalCNF cnf v).2 hv⟩

/-- Constructor success iff CNF satisfies the common-factor criterion. -/
theorem deterministicBreadthRun_nonempty_iff_CNFSharesFactor {k : ℕ}
    (cnf : SyntacticCNF_EGPT k) :
    (deterministicBreadthRun cnf).Nonempty ↔ EGPT.Complexity.CNFSharesFactor cnf := by
  constructor
  · rintro ⟨v, hv⟩
    exact (EGPT.Complexity.cnfSharesFactor_of_exists_assignment (cnf := cnf))
      ⟨v, (mem_deterministicBreadthRun_iff_evalCNF cnf v).1 hv⟩
  · intro h_cf
    rcases (EGPT.Complexity.exists_assignment_of_cnfSharesFactor (cnf := cnf) h_cf) with ⟨v, hv⟩
    exact ⟨v, (mem_deterministicBreadthRun_iff_evalCNF cnf v).2 hv⟩

/-!
### Survivor Programs (The PProgram)

The PProgram records surviving particle paths as deterministic programs.
`verify_via_constructedSet_iff_evalCNF` proves that the PProgram serves
as an NP polynomial witness verifier (Exchange 17, IN13).
-/

/-- Program projection of a terminal survivor assignment. -/
def survivorProgram {k : ℕ} (v : Vector Bool k) : ComputerProgram :=
  encodeCNF (cnf_for_specific_assignment v)

/-- Ordered list of survivor programs extracted from terminal survivor set. -/
noncomputable def survivorPrograms {k : ℕ} (cnf : SyntacticCNF_EGPT k) : List ComputerProgram :=
  (deterministicBreadthRun cnf).toList.map survivorProgram

/-- Composition (sum) of all survivor programs. -/
noncomputable def composeSurvivorPrograms {k : ℕ} (cnf : SyntacticCNF_EGPT k) : ComputerProgram :=
  (survivorPrograms cnf).foldl combinePrograms []

/-- Composed survivor output is definitionally a `ComputerProgram`. -/
theorem composeSurvivorPrograms_is_program {k : ℕ} (cnf : SyntacticCNF_EGPT k) :
    ∃ prog : ComputerProgram, prog = composeSurvivorPrograms cnf := by
  exact ⟨composeSurvivorPrograms cnf, rfl⟩

/-!
### Theorem D: NDM Terminal States = Breadth Construction Survivors

Any state that satisfies all constraints (as produced by NDTM_A_run or any
other means) is in the deterministic breadth run's survivor set, and vice versa.
This connects the non-deterministic particle transport to the deterministic
clause-by-clause filtering.
-/

/-- NDM-to-breadth equivalence: evalCNF = membership in deterministicBreadthRun. -/
theorem ndm_survivors_eq_breadth_survivors {k : ℕ}
    (cnf : SyntacticCNF_EGPT k) (v : Vector Bool k) :
    evalCNF cnf v = true ↔ v ∈ deterministicBreadthRun cnf :=
  (mem_deterministicBreadthRun_iff_evalCNF cnf v).symm

/-!
### Theorem B: Survivor Programs Have Polynomial Time Complexity

Each survivor program encodes a single assignment as a CNF with k unit clauses.
Its time complexity (= tape length by `timeComplexity_eq_length`) is bounded
by the encoding size, which is polynomial in k.
-/

/--
The CNF for a specific assignment has exactly k clauses (one per variable).
-/
theorem cnf_for_specific_assignment_length {k : ℕ} (v : Vector Bool k) :
    (cnf_for_specific_assignment v).length = k := by
  simp [cnf_for_specific_assignment]

/--
**Theorem B: Survivor program time complexity is polynomial.**

Each survivor program's time complexity equals its tape length (by
`timeComplexity_eq_length`), which is the encoding of a k-clause CNF.
The encoding size is bounded by k * (encoding overhead per unit clause).
This is O(k) — polynomial in the number of variables.
-/
theorem survivorProgram_timeComplexity_eq_encoding {k : ℕ} (v : Vector Bool k) :
    timeComplexity (survivorProgram v) = (encodeCNF (cnf_for_specific_assignment v)).length := by
  simp [survivorProgram, timeComplexity_eq_length]

/-!
### Theorem C: Per-Clause Walk Cost Is Bounded by k (Independent of Clause Interaction)

The walk processes one clause per step. Each clause's literal index is a `Fin k`,
so `PathToConstraint lit` = `fromNat lit.particle_idx.val` which has length < k.
The per-clause cost depends only on the clause's literal structure, NOT on how
previous clauses constrained the viable set. This is the formal statement that
the walk performs conditional reductions without computing conditional distributions.
-/

/--
**Theorem C: Per-clause walk cost is bounded by k.**

Each clause's contribution to the walk cost is bounded by k because literal
indices are `Fin k`. The cost is structural — it depends on the clause's literal
addresses, not on the survivor set from prior clauses. This directly addresses
the Skeptic's #P objection: the walk does not compute conditional distributions,
it performs conditional reductions at fixed cost per clause.

Combined with `walkComplexity_upper_bound` (which bounds total cost at
`|cnf| × k`), this shows the walk is polynomial regardless of clause
interaction structure.
-/
theorem walk_per_clause_cost_independent_of_history {k : ℕ}
    (cnf : SyntacticCNF_EGPT k)
    (endpoint : { v : Vector Bool k // evalCNF cnf v = true }) :
    -- Total walk cost is bounded by |cnf| × k
    (walkCNFPaths cnf endpoint).complexity ≤ cnf.length * k ∧
    -- This bound depends only on |cnf| and k, not on the assignment
    ∀ (endpoint' : { v : Vector Bool k // evalCNF cnf v = true }),
      (walkCNFPaths cnf endpoint').complexity ≤ cnf.length * k := by
  exact ⟨walkComplexity_upper_bound cnf endpoint,
         fun endpoint' => walkComplexity_upper_bound cnf endpoint'⟩

/-! ## Chain 1 declarations resumed — NDM address walk, entropy walk, circuit eval

The remaining declarations below ARE part of the P=NP proof chain (Chain 1).
They are directly imported by `PPNP.lean`: `literalAddress`,
`literalAddressPath`, `ndmAddressWalk`, `ndmWalkComplexity`,
`NDMEntropyWalkState`, `ndmEntropyWalk`, `ndmEntropyWalk_*` theorems,
`ndmCircuitEval`, `ndmCircuitEval_eq_evalCNF`, `ndmCircuit_entropy_bridge`,
`ndmCircuit_sat_iff`, `ndmCircuit_cost_polynomial`, and
`ndmWalkComplexity_polynomial`.
-/

/-!
==================================================================
# NDM Address-Space Walk (Exchange 18)

## The Fundamental Correction

The previous `walkCNFPaths` formulation was wrong: it took an `endpoint`
parameter (a satisfying assignment) as INPUT. This is the NP verification
direction — given a solution, check it. It does not capture the P direction
— find a solution without one being given.

The previous `deterministicBreadthRun` was also wrong: it started from
`Finset.univ : Finset (Vector Bool k)`, which has 2^k elements. The cost
model hid exponential work inside `Finset.filter`.

## The Correct NDM Formulation

The NDM machine navigates in **maximally compressed information space**
(ParticlePath). At each tick t_i:

- The machine's state is a ParticlePath address
- States are memoryless (`underlying_state_evolution_is_memoryless`)
- Addresses are unique: `fromNat n = replicate n true`, `toNat = length`
- At depth t_i in a binary tree: 2^t_i paths compress to t_i+1 addresses
  (Shannon Coding Theorem — C18)

## Polarity-Encoded Addresses (Option A)

Literal addresses encode BOTH variable AND polarity via `Literal_EGPT.toNat`:

  `toNat lit = 2 * lit.particle_idx.val + (if lit.polarity then 1 else 0)`

This gives **2k unique addresses** (linear in k, NOT exponential).
Variable x₁ positive → address 3, x₁ negative → address 2. Different
addresses for different polarities. The address space is linear.

## Walk Structure

For each clause in the CNF, the walk records the polarity-encoded
ParticlePath addresses of ALL literals in that clause. No endpoint
parameter. The walk's output is the complete address structure of the CNF.

The walk cost = sum of literal address values across all clauses.
Each literal address < 2k, each clause has ≤ k literals, so:

  walk cost ≤ |cnf| × k × 2k = 2 × |cnf| × k²

This is polynomial in the input size n = |encodeCNF cnf|.
==================================================================
-/

/--
**Polarity-encoded literal address.**

Maps each literal to a unique ℕ address encoding both variable position
AND polarity. For k variables, there are 2k addresses: {0, 1, ..., 2k-1}.

- `(x_i, true)` → `2i + 1` (odd addresses = positive polarity)
- `(x_i, false)` → `2i` (even addresses = negative polarity)

This is the existing `Literal_EGPT.toNat` from Constraints.lean.
-/
def literalAddress {k : ℕ} (lit : Literal_EGPT k) : ℕ :=
  Literal_EGPT.toNat lit

/--
**Literal address as a ParticlePath.**

Each literal address `n` maps to `fromNat n = replicate n true` —
a ParticlePath of length `n`. The walk records these addresses.
-/
def literalAddressPath {k : ℕ} (lit : Literal_EGPT k) : ParticlePath :=
  fromNat (literalAddress lit)

/--
**Each literal address is bounded by 2k.**

Since `lit.particle_idx : Fin k`, we have `lit.particle_idx.val < k`,
so `literalAddress lit = 2 * lit.particle_idx.val + (0 or 1) < 2k`.
-/
theorem literalAddress_lt_two_k {k : ℕ} (lit : Literal_EGPT k) :
    literalAddress lit < 2 * k := by
  simp only [literalAddress, Literal_EGPT.toNat]
  have h := lit.particle_idx.isLt
  by_cases hp : lit.polarity <;> simp [hp] <;> omega

/--
**Literal address path length is bounded by 2k.**
-/
theorem literalAddressPath_length_lt_two_k {k : ℕ} (lit : Literal_EGPT k) :
    toNat (literalAddressPath lit) < 2 * k := by
  simp only [literalAddressPath, left_inv]
  exact literalAddress_lt_two_k lit

/--
**The set of all literal addresses for k variables.**

Contains 2k addresses: {0, 1, ..., 2k-1}. This is LINEAR in k.
Compare with `Finset.univ : Finset (Vector Bool k)` which has 2^k elements.
-/
def allLiteralAddresses (k : ℕ) : Finset ℕ :=
  Finset.range (2 * k)

/-- The literal address set has exactly 2k elements. -/
theorem allLiteralAddresses_card (k : ℕ) :
    (allLiteralAddresses k).card = 2 * k := by
  simp [allLiteralAddresses]

/-- Every literal address is a member of `allLiteralAddresses`. -/
theorem literalAddress_mem_allLiteralAddresses {k : ℕ} (lit : Literal_EGPT k) :
    literalAddress lit ∈ allLiteralAddresses k := by
  simp [allLiteralAddresses, Finset.mem_range]
  exact literalAddress_lt_two_k lit

/--
**Clause address set: the polarity-encoded addresses in a clause.**

For a clause with literals l₁, ..., lₘ, this is {toNat l₁, ..., toNat lₘ}.
Size ≤ |clause| ≤ k.
-/
def clauseAddressSet {k : ℕ} (clause : Clause_EGPT k) : Finset ℕ :=
  (clause.map literalAddress).toFinset

/-- Clause address set size is bounded by clause length. -/
theorem clauseAddressSet_card_le {k : ℕ} (clause : Clause_EGPT k) :
    (clauseAddressSet clause).card ≤ clause.length := by
  unfold clauseAddressSet
  calc (clause.map literalAddress).toFinset.card
    ≤ (clause.map literalAddress).length := List.toFinset_card_le _
    _ = clause.length := List.length_map ..

/--
**NDM address-space walk: endpoint-free clause-by-clause address recording.**

For each clause in the CNF, records the ParticlePath addresses of ALL
literals in that clause. No endpoint parameter. The walk processes all
clauses and records the complete polarity-encoded address structure.

The output is `List (List ParticlePath)` — one list of addresses per clause.
This replaces `walkCNFPaths` (which requires an endpoint) with an
endpoint-free formulation operating on 2k addresses (linear) instead of
2^k assignments (exponential).
-/
def ndmAddressWalk {k : ℕ} (cnf : SyntacticCNF_EGPT k) : List (List ParticlePath) :=
  cnf.map (fun clause => clause.map literalAddressPath)

/-- The address walk visits every clause (exhaustive). -/
theorem ndmAddressWalk_length {k : ℕ} (cnf : SyntacticCNF_EGPT k) :
    (ndmAddressWalk cnf).length = cnf.length := by
  simp [ndmAddressWalk]

/-- Per-clause address list length equals clause length. -/
theorem ndmAddressWalk_clause_lengths {k : ℕ} (cnf : SyntacticCNF_EGPT k)
    (addressPaths : List ParticlePath) (h_mem : addressPaths ∈ ndmAddressWalk cnf) :
    ∃ clause ∈ cnf, addressPaths.length = clause.length := by
  simp [ndmAddressWalk] at h_mem
  obtain ⟨clause, h_clause_mem, h_eq⟩ := h_mem
  exact ⟨clause, h_clause_mem, by rw [← h_eq]; simp⟩

/--
**NDM walk complexity: total ParticlePath address cost.**

The complexity is the sum of all literal address values across all clauses.
Each address value = `toNat (literalAddressPath lit)` = `literalAddress lit`.
-/
def ndmWalkComplexity {k : ℕ} (cnf : SyntacticCNF_EGPT k) : ℕ :=
  ((ndmAddressWalk cnf).map (fun paths => (paths.map toNat).sum)).sum

/--
**Per-clause address cost is bounded by |clause| × 2k.**

Each literal address < 2k, so the sum of addresses in a clause
with m literals is < m × 2k.
-/
theorem clause_address_cost_le {k : ℕ} (clause : Clause_EGPT k) :
    ((clause.map literalAddressPath).map toNat).sum ≤ clause.length * (2 * k) := by
  rw [List.map_map]
  apply sum_map_le_length_mul_bound
  intro lit h_mem
  simp only [Function.comp]
  simp only [literalAddressPath, left_inv]
  exact Nat.le_of_lt (literalAddress_lt_two_k lit)

/--
**NDM walk complexity is polynomial: bounded by |cnf| × k × 2k.**

Total cost = sum over clauses of (sum of literal addresses in clause).
Each clause has ≤ k literals, each literal address < 2k.
So total ≤ |cnf| × k × 2k = 2 × |cnf| × k².

This is polynomial in n = |encodeCNF cnf| (since |cnf| ≤ n and k ≤ n).
-/
theorem ndmWalkComplexity_polynomial {k : ℕ} (cnf : SyntacticCNF_EGPT k)
    (h_clause_bound : ∀ c ∈ cnf, c.length ≤ k) :
    ndmWalkComplexity cnf ≤ cnf.length * (k * (2 * k)) := by
  unfold ndmWalkComplexity ndmAddressWalk
  simp only [List.map_map]
  induction cnf with
  | nil => simp
  | cons head tail ih =>
    simp only [List.map_cons, List.sum_cons, List.length_cons]
    have h_head_bound : head.length ≤ k :=
      h_clause_bound head (List.mem_cons.mpr (Or.inl rfl))
    have h_tail_bound : ∀ c ∈ tail, c.length ≤ k :=
      fun c hc => h_clause_bound c (List.mem_cons.mpr (Or.inr hc))
    have h_head_cost : ((head.map literalAddressPath).map toNat).sum ≤ k * (2 * k) := by
      calc ((head.map literalAddressPath).map toNat).sum
        ≤ head.length * (2 * k) := clause_address_cost_le head
        _ ≤ k * (2 * k) := Nat.mul_le_mul_right _ h_head_bound
    have h_tail_cost := ih h_tail_bound
    simp only [Function.comp, List.map_map] at h_head_cost h_tail_cost ⊢
    linarith

/--
**Address-space breadth at step t: the number of viable ParticlePath
addresses after processing t clauses.**

At depth t_i in the binary tree:
- Uncompressed: 2^t_i possible paths
- ParticlePath (Shannon-compressed): bounded by 2k addresses

The breadth never exceeds 2k (the total literal address space),
which is LINEAR in k. This is the honest polynomial cost model:
filtering 2k addresses per clause costs O(k), not O(2^k).
-/
def addressBreadthStep {k : ℕ} (clause : Clause_EGPT k)
    (active : Finset ℕ) : Finset ℕ :=
  active.filter (fun addr =>
    clause.any (fun lit => decide (literalAddress lit = addr)))

/--
**Address-space breadth run: starts from 2k addresses.**

This replaces `deterministicBreadthRun` which starts from
`Finset.univ : Finset (Vector Bool k)` (2^k elements).

The address-space version starts from `allLiteralAddresses k` (2k elements)
and filters clause by clause. At each step, the active set is a subset
of {0, ..., 2k-1}, so the filtering cost is O(k) per clause.
-/
def addressSpaceBreadthRun {k : ℕ} (cnf : SyntacticCNF_EGPT k) : Finset ℕ :=
  cnf.foldl (fun active clause => addressBreadthStep clause active)
    (allLiteralAddresses k)

/-- Address breadth step preserves the subset property. -/
theorem addressBreadthStep_subset {k : ℕ} (clause : Clause_EGPT k)
    (active : Finset ℕ) :
    addressBreadthStep clause active ⊆ active := by
  simp [addressBreadthStep, Finset.filter_subset]

/-- Helper: foldl of addressBreadthStep preserves subset from any starting set. -/
private theorem addressBreadthStep_foldl_subset {k : ℕ}
    (cnf : List (Clause_EGPT k)) (init : Finset ℕ) :
    cnf.foldl (fun active clause => addressBreadthStep clause active) init ⊆ init := by
  induction cnf generalizing init with
  | nil => simp
  | cons head tail ih =>
    simp only [List.foldl_cons]
    exact Finset.Subset.trans (ih _) (addressBreadthStep_subset head init)

/-- The address-space breadth run result is a subset of allLiteralAddresses. -/
theorem addressSpaceBreadthRun_subset {k : ℕ} (cnf : SyntacticCNF_EGPT k) :
    addressSpaceBreadthRun cnf ⊆ allLiteralAddresses k := by
  exact addressBreadthStep_foldl_subset cnf (allLiteralAddresses k)

/--
**Address breadth is bounded by 2k (linear).**

The active address set at each step is a subset of `allLiteralAddresses k`,
which has 2k elements. This is the polynomial breadth bound.
-/
theorem addressSpaceBreadth_le_two_k {k : ℕ} (cnf : SyntacticCNF_EGPT k) :
    (addressSpaceBreadthRun cnf).card ≤ 2 * k := by
  calc (addressSpaceBreadthRun cnf).card
      ≤ (allLiteralAddresses k).card := Finset.card_le_card (addressSpaceBreadthRun_subset cnf)
    _ = 2 * k := allLiteralAddresses_card k

/--
**Address-space breadth cost: O(|cnf| × 2k).**

At each clause, filtering 2k addresses costs O(2k). Over |cnf| clauses,
the total cost is |cnf| × 2k. This is polynomial.
-/
def addressSpaceBreadthCost {k : ℕ} (cnf : SyntacticCNF_EGPT k) : ℕ :=
  cnf.length * (2 * k)

/--
**The address-space breadth cost is polynomial in encoded input size.**
-/
theorem addressSpaceBreadthCost_polynomial {k : ℕ} (cnf : SyntacticCNF_EGPT k) :
    addressSpaceBreadthCost cnf ≤
      2 * ((encodeCNF cnf).length * (encodeCNF cnf).length) := by
  unfold addressSpaceBreadthCost
  calc cnf.length * (2 * k)
    = 2 * (cnf.length * k) := by ring
    _ ≤ 2 * ((encodeCNF cnf).length * (encodeCNF cnf).length) := by
      apply Nat.mul_le_mul_left
      exact Nat.mul_le_mul (cnf_length_le_encoded_length cnf) (encodeCNF_size_ge_k k cnf)

/--
**Connection: literalAddress extends PathToConstraint with polarity.**

`PathToConstraint lit = fromNat lit.particle_idx.val` records only the
variable position (k addresses). `literalAddressPath lit = fromNat (literalAddress lit)`
records variable AND polarity (2k addresses). The polarity-encoded version
is a refinement: `literalAddress lit = 2 * (toNat (PathToConstraint lit)) + polarity_bit`.
-/
theorem literalAddress_refines_PathToConstraint {k : ℕ} (lit : Literal_EGPT k) :
    literalAddress lit =
      2 * (toNat (PathToConstraint lit)) + (if lit.polarity then 1 else 0) := by
  simp [literalAddress, Literal_EGPT.toNat, PathToConstraint, left_inv]

/--
**The NDM address walk IS the endpoint-free computation.**

In the EGPT computation model, the walk through clause addresses
IS the computation. The walk does not need an endpoint because:

1. The walk records ALL literal addresses per clause (complete information)
2. The address space is linear (2k addresses, not 2^k assignments)
3. The walk cost = information content (RECT/IRECT)
4. The information content determines satisfiability (Theorem A:
   `cnfSharesFactor_iff_zero_conditional_cnf_entropy`)

The walk's output (`List (List ParticlePath)`) flattens to
`List (List Bool)` → `List Bool` = `ComputerTape` = `ComputerProgram`.
The walk IS the program. The address IS the map.
-/
theorem ndmAddressWalk_is_program {k : ℕ} (cnf : SyntacticCNF_EGPT k) :
    ∃ prog : ComputerProgram,
      prog = List.flatten ((ndmAddressWalk cnf).map
        (fun paths => List.flatten (paths.map (fun p => p.val)))) := by
  exact ⟨_, rfl⟩

/--
**The walk program's time complexity equals the walk's information cost.**

By `timeComplexity_eq_length`, reading the walk program tape costs
exactly its length — one step per bit. The length equals the sum
of all literal address ParticlePath lengths across all clauses.
This IS the `ndmWalkComplexity`.
-/
theorem ndmWalkProgram_timeComplexity {k : ℕ} (cnf : SyntacticCNF_EGPT k) :
    let prog := List.flatten ((ndmAddressWalk cnf).map
      (fun paths => List.flatten (paths.map (fun p => p.val))))
    timeComplexity prog = ndmWalkComplexity cnf := by
  -- Helper: for any list of ParticlePaths, flattening their vals has length = sum of toNat
  suffices inner : ∀ (paths : List ParticlePath),
      (List.flatten (paths.map (fun p => p.val))).length = (paths.map toNat).sum by
    simp only [timeComplexity_eq_length, ndmWalkComplexity, ndmAddressWalk]
    rw [List.length_flatten, List.map_map]
    congr 1
    apply List.map_congr_left
    intro clause _
    simp only [Function.comp]
    exact inner _
  intro paths
  rw [List.length_flatten, List.map_map]
  rfl

/-!
### NDM Entropy Walk: Conditional Entropy Inside the Machine

The conditional entropy decomposition from Decomposition.lean
(`conditionalCNFEntropy`, `cnfSharesFactor_iff_zero_conditional_cnf_entropy`)
characterizes SAT as total conditional entropy = 0. Previously, this was
an external characterization applied after the walk.

The NDM entropy walk INTERNALIZES this: the walk machine carries the
conditional entropy accumulator as it processes clauses. At each clause,
the walk simultaneously:

1. Records literal addresses (the `ndmAddressWalk` component)
2. Computes the conditional clause entropy (the chain rule component)
3. Accumulates the total entropy (the SAT-determination component)

**Chain rule inside the machine:** The walk's clause-by-clause entropy
accumulation IS the chain rule decomposition C6/C17:

  H(CNF | composite) = Σⱼ H(clauseⱼ | composite)

Each step adds `conditionalClauseEntropy composite clauseⱼ` to the running
total. The walk's final total equals `conditionalCNFEntropy composite cnf`.

**Addressing Rota's marginal-vs-joint objection:** The per-address filtering
in `addressBreadthStep` treats addresses independently (marginal). The
conditional entropy decomposition handles JOINT consistency because:
- `conditionalClauseEntropy composite clause = 0` iff some literal's prime
  divides the composite — this IS joint consistency (the composite encodes
  a full variable assignment)
- The chain rule preserves this joint structure across clauses

The walk is parameterized by the assignment composite. In the NDM particle
transport model, each particle path corresponds to a composite, and the
walk processes all 2k literal addresses per clause at cost proportional
to the address count (2k), not the path count (2^k).
-/

/-- State of the NDM entropy walk: carries the walk's address record
    alongside the conditional entropy accumulation. -/
structure NDMEntropyWalkState (k : ℕ) where
  /-- The composite being tested (encodes the variable assignment) -/
  composite : ℕ
  /-- Running total of conditional entropy across processed clauses -/
  totalEntropy : ℝ
  /-- Per-clause conditional entropy contributions (chain rule terms) -/
  clauseEntropies : List ℝ
  /-- Literal addresses recorded per clause (the ndmAddressWalk component) -/
  addressRecord : List (List ParticlePath)

/-- Initialize the entropy walk state with a composite. -/
noncomputable def NDMEntropyWalkState.init {k : ℕ} (composite : ℕ) :
    NDMEntropyWalkState k :=
  { composite := composite
    totalEntropy := 0
    clauseEntropies := []
    addressRecord := [] }

/--
One step of the NDM entropy walk: process a single clause.

Simultaneously:
1. Records the clause's literal addresses (address walk component)
2. Computes `conditionalClauseEntropy composite clause` (entropy component)
3. Adds the clause entropy to the running total (chain rule accumulation)

The conditional clause entropy is zero iff some literal's prime divides
the composite (i.e., the clause is satisfied by the encoded assignment).
This is the per-clause conditional entropy from Decomposition.lean,
now computed inside the machine at each step.
-/
noncomputable def ndmEntropyStep {k : ℕ} (clause : Clause_EGPT k)
    (state : NDMEntropyWalkState k) : NDMEntropyWalkState k :=
  let clauseAddresses := clause.map literalAddressPath
  let clauseH := conditionalClauseEntropy state.composite clause
  { state with
    totalEntropy := state.totalEntropy + clauseH
    clauseEntropies := state.clauseEntropies ++ [clauseH]
    addressRecord := state.addressRecord ++ [clauseAddresses] }

/--
The full NDM entropy walk: process all clauses sequentially.

The walk folds over the CNF clause by clause, simultaneously recording
literal addresses and accumulating conditional entropy. This is the
chain rule decomposition H(CNF | composite) = Σⱼ H(clauseⱼ | composite)
computed inside the machine as it walks.
-/
noncomputable def ndmEntropyWalk {k : ℕ} (cnf : SyntacticCNF_EGPT k)
    (composite : ℕ) : NDMEntropyWalkState k :=
  cnf.foldl (fun state clause => ndmEntropyStep clause state)
    (NDMEntropyWalkState.init composite)

/-- The composite field is preserved by ndmEntropyStep. -/
private theorem ndmEntropyStep_composite {k : ℕ} (clause : Clause_EGPT k)
    (state : NDMEntropyWalkState k) :
    (ndmEntropyStep clause state).composite = state.composite := by
  simp [ndmEntropyStep]

/-- The composite field is preserved by the full foldl walk. -/
private theorem ndmEntropyWalk_foldl_composite {k : ℕ}
    (cnf : List (Clause_EGPT k)) (init : NDMEntropyWalkState k) :
    (cnf.foldl (fun state clause => ndmEntropyStep clause state) init).composite =
      init.composite := by
  induction cnf generalizing init with
  | nil => simp
  | cons head tail ih =>
    simp only [List.foldl_cons]
    rw [ih, ndmEntropyStep_composite]

/-- Helper: the foldl accumulation pattern for totalEntropy. -/
private theorem ndmEntropyWalk_foldl_total {k : ℕ}
    (cnf : List (Clause_EGPT k)) (init : NDMEntropyWalkState k) :
    (cnf.foldl (fun state clause => ndmEntropyStep clause state) init).totalEntropy =
      init.totalEntropy + (cnf.map (conditionalClauseEntropy init.composite)).sum := by
  induction cnf generalizing init with
  | nil => simp
  | cons head tail ih =>
    simp only [List.foldl_cons, List.map_cons, List.sum_cons]
    rw [ih]
    simp only [ndmEntropyStep, ndmEntropyStep_composite]
    ring

/--
**The entropy walk's total equals the conditional CNF entropy.**

The walk accumulates exactly `conditionalCNFEntropy composite cnf`:
each clause step adds `conditionalClauseEntropy composite clause` to
the running total, and the sum is the conditional CNF entropy.

This is the chain rule identity C6/C17 proven as a property of the
walk machine — the decomposition IS the machine's operation.
-/
theorem ndmEntropyWalk_total_eq {k : ℕ} (cnf : SyntacticCNF_EGPT k)
    (composite : ℕ) :
    (ndmEntropyWalk cnf composite).totalEntropy =
      conditionalCNFEntropy composite cnf := by
  unfold ndmEntropyWalk
  rw [ndmEntropyWalk_foldl_total]
  simp [NDMEntropyWalkState.init, conditionalCNFEntropy]

/--
**The entropy walk determines SAT.**

The NDM entropy walk's total entropy is zero iff the CNF is satisfiable
under the assignment encoded by the composite. This theorem chains:

1. Walk total = `conditionalCNFEntropy` (by `ndmEntropyWalk_total_eq`)
2. `conditionalCNFEntropy = 0 ↔ cnfSharesFactor` (by Decomposition.lean bridge)
3. `cnfSharesFactor ↔ evalCNF = true` (by `evalCNF_true_iff_cnfSharesFactor`)

The conditional entropy decomposition INSIDE the walk machine determines
satisfiability. The walk processes each clause once at cost O(k) per clause,
total cost O(|cnf| × k) — polynomial.
-/
theorem ndmEntropyWalk_determines_sat {k : ℕ} (cnf : SyntacticCNF_EGPT k)
    (a : Vector Bool k) (h_clauses_nonempty : ∀ c ∈ cnf, c ≠ []) :
    (ndmEntropyWalk cnf (assignmentCompositePrime a)).totalEntropy = 0 ↔
      evalCNF cnf a = true := by
  rw [ndmEntropyWalk_total_eq]
  exact (cnfSharesFactor_iff_zero_conditional_cnf_entropy a cnf h_clauses_nonempty).symm.trans
    (evalCNF_true_iff_cnfSharesFactor a cnf).symm

/-- Helper: the foldl accumulation pattern for addressRecord. -/
private theorem ndmEntropyWalk_foldl_addressRecord {k : ℕ}
    (cnf : List (Clause_EGPT k)) (init : NDMEntropyWalkState k) :
    (cnf.foldl (fun state clause => ndmEntropyStep clause state) init).addressRecord =
      init.addressRecord ++ cnf.map (fun clause => clause.map literalAddressPath) := by
  induction cnf generalizing init with
  | nil => simp
  | cons head tail ih =>
    simp only [List.foldl_cons, List.map_cons]
    rw [ih]
    simp [ndmEntropyStep, List.append_assoc]

/--
**The entropy walk's address record equals the NDM address walk.**

The entropy walk simultaneously records literal addresses and computes
entropy. The address component is identical to `ndmAddressWalk`.
-/
theorem ndmEntropyWalk_addresses_eq {k : ℕ} (cnf : SyntacticCNF_EGPT k)
    (composite : ℕ) :
    (ndmEntropyWalk cnf composite).addressRecord = ndmAddressWalk cnf := by
  unfold ndmEntropyWalk ndmAddressWalk
  rw [ndmEntropyWalk_foldl_addressRecord]
  simp [NDMEntropyWalkState.init]

/--
**The entropy walk's per-clause contributions are non-negative.**

Each clause's conditional entropy contribution is ≥ 0 (by
`conditionalClauseEntropy_nonneg` from Decomposition.lean).
-/
theorem ndmEntropyWalk_nonneg {k : ℕ} (cnf : SyntacticCNF_EGPT k)
    (composite : ℕ) :
    0 ≤ (ndmEntropyWalk cnf composite).totalEntropy := by
  rw [ndmEntropyWalk_total_eq]
  unfold conditionalCNFEntropy
  exact List.sum_nonneg (fun x hx => by
    rw [List.mem_map] at hx
    rcases hx with ⟨clause, _, rfl⟩
    exact conditionalClauseEntropy_nonneg composite clause)

/--
**The entropy walk cost is polynomial.**

The address walk component of the entropy walk has the same cost as
`ndmWalkComplexity` (proven polynomial by `ndmWalkComplexity_polynomial`).
The entropy computation adds O(1) per clause (one ℝ addition), which
doesn't change the polynomial bound.
-/
theorem ndmEntropyWalk_cost_polynomial {k : ℕ} (cnf : SyntacticCNF_EGPT k)
    (h_clause_bound : ∀ c ∈ cnf, c.length ≤ k) :
    ndmWalkComplexity cnf ≤ cnf.length * (k * (2 * k)) :=
  ndmWalkComplexity_polynomial cnf h_clause_bound

/--
**SAT ↔ ∃ composite with zero entropy walk.**

Combining `ndmEntropyWalk_determines_sat` with the existential:
the CNF is satisfiable iff there exists a composite (assignment encoding)
for which the entropy walk produces zero total entropy.

This is the information-theoretic SAT criterion computed inside the machine.
The walk processes each clause once; the entropy output determines SAT.
The composite parameter connects to the NDM particle transport model:
each particle carries a composite, and the walk processes all particles
via the 2k literal address space.
-/
theorem ndmEntropyWalk_sat_iff_exists_zero {k : ℕ} (cnf : SyntacticCNF_EGPT k)
    (h_clauses_nonempty : ∀ c ∈ cnf, c ≠ []) :
    (∃ a : Vector Bool k, (ndmEntropyWalk cnf (assignmentCompositePrime a)).totalEntropy = 0) ↔
      (∃ a : Vector Bool k, evalCNF cnf a = true) := by
  constructor
  · rintro ⟨a, h_zero⟩
    exact ⟨a, (ndmEntropyWalk_determines_sat cnf a h_clauses_nonempty).mp h_zero⟩
  · rintro ⟨a, h_sat⟩
    exact ⟨a, (ndmEntropyWalk_determines_sat cnf a h_clauses_nonempty).mpr h_sat⟩

/-- Helper: the foldl accumulation pattern for clauseEntropies length. -/
private theorem ndmEntropyWalk_foldl_clauseEntropies_length {k : ℕ}
    (cnf : List (Clause_EGPT k)) (init : NDMEntropyWalkState k) :
    (cnf.foldl (fun state clause => ndmEntropyStep clause state) init).clauseEntropies.length =
      init.clauseEntropies.length + cnf.length := by
  induction cnf generalizing init with
  | nil => simp
  | cons head tail ih =>
    simp only [List.foldl_cons, List.length_cons]
    rw [ih]
    simp [ndmEntropyStep, List.length_append]
    omega

/--
**The entropy walk clause count equals the CNF clause count.**

The walk processes exactly |cnf| clauses, recording one entropy
contribution per clause.
-/
theorem ndmEntropyWalk_clauseEntropies_length {k : ℕ} (cnf : SyntacticCNF_EGPT k)
    (composite : ℕ) :
    (ndmEntropyWalk cnf composite).clauseEntropies.length = cnf.length := by
  unfold ndmEntropyWalk
  rw [ndmEntropyWalk_foldl_clauseEntropies_length]
  simp [NDMEntropyWalkState.init]

/-!
==================================================================
# Circuit SAT via NDM Address Space (Exchange 19)

## The Key Insight

The existing `addressBreadthStep` intersects individual addresses,
but SAT requires ONE literal per clause, not ALL addresses to survive.
The correct formulation tracks which VARIABLE ASSIGNMENTS remain
consistent, not which individual literal addresses survive every clause.

The NDM circuit model:
- INPUTS: the variable literal addresses (2k total, k selected by any assignment)
- CONSTRAINTS: the CNF clauses (each clause specifies which literal addresses satisfy it)
- OUTPUT: whether the selected input addresses are consistent with all constraints

## Architecture

1. `literalAddressesFromAssignment` — the k addresses selected by assignment a
2. `ndmCircuitEval` — circuit evaluation in address space
3. `ndmCircuitEval_eq_evalCNF` — the NDM circuit IS evalCNF (capstone)
4. Polynomial cost and memoryless properties
==================================================================
-/

/--
**Extract assignment from literal addresses.**

Reads the polarity bit: if address `2i+1` (positive literal) is in the
set, variable i = true; otherwise false. Connects to
`literalAddress lit = 2 * lit.particle_idx.val + (if lit.polarity then 1 else 0)`.
-/
def assignmentFromAddresses (k : ℕ) (addresses : Finset ℕ) : Vector Bool k :=
  Vector.ofFn (fun i => (2 * i.val + 1) ∈ addresses)

/--
**The addresses selected by an assignment.**

For each variable index i, the assignment selects the literal
`chosenLiteral a i`, and its address is `literalAddress (chosenLiteral a i)`.
This gives exactly k literal addresses.
-/
def literalAddressesFromAssignment {k : ℕ} (a : Vector Bool k) : Finset ℕ :=
  Finset.image (fun i => literalAddress (chosenLiteral a i)) Finset.univ

/--
**Selected addresses are within the literal address space.**
-/
theorem literalAddressesFromAssignment_subset {k : ℕ} (a : Vector Bool k) :
    literalAddressesFromAssignment a ⊆ allLiteralAddresses k := by
  intro addr h_mem
  simp only [literalAddressesFromAssignment, Finset.mem_image, Finset.mem_univ, true_and] at h_mem
  rcases h_mem with ⟨i, rfl⟩
  exact literalAddress_mem_allLiteralAddresses (chosenLiteral a i)

/--
**Exactly k addresses are selected (at most).**
-/
theorem literalAddressesFromAssignment_card_le {k : ℕ} (a : Vector Bool k) :
    (literalAddressesFromAssignment a).card ≤ k := by
  unfold literalAddressesFromAssignment
  calc (Finset.image (fun i => literalAddress (chosenLiteral a i)) Finset.univ).card
      ≤ Finset.univ.card := Finset.card_image_le
    _ = k := Finset.card_fin k

/--
**The fundamental bridge: `evalLiteral lit a = true` iff
`literalAddress lit ∈ literalAddressesFromAssignment a`.**

This follows from the polarity encoding: `literalAddress lit = 2 * idx + polarity_bit`,
and `literalAddressesFromAssignment` selects `2 * idx + (a.get idx)_bit`,
so membership iff `lit.polarity = a.get(lit.particle_idx)` iff `evalLiteral lit a = true`.
-/
theorem evalLiteral_iff_mem_literalAddresses {k : ℕ} (lit : Literal_EGPT k)
    (a : Vector Bool k) :
    evalLiteral lit a = true ↔
      literalAddress lit ∈ literalAddressesFromAssignment a := by
  constructor
  · intro h_eval
    have h_pol := (evalLiteral_eq_true_iff_polarity_eq lit a).mp h_eval
    simp only [literalAddressesFromAssignment, Finset.mem_image, Finset.mem_univ, true_and]
    refine ⟨lit.particle_idx, ?_⟩
    -- Need: literalAddress lit = literalAddress (chosenLiteral a lit.particle_idx)
    -- Since lit.polarity = a.get lit.particle_idx, the chosen literal matches
    simp only [literalAddress, Literal_EGPT.toNat, chosenLiteral, h_pol]
  · intro h_mem
    simp only [literalAddressesFromAssignment, Finset.mem_image, Finset.mem_univ, true_and] at h_mem
    rcases h_mem with ⟨i, h_addr_eq⟩
    -- h_addr_eq : literalAddress lit = literalAddress (chosenLiteral a i)
    simp only [literalAddress, Literal_EGPT.toNat, chosenLiteral] at h_addr_eq
    -- h_addr_eq : 2 * lit.particle_idx.val + (if lit.polarity = true then 1 else 0) =
    --             2 * i.val + (if (a.get i) = true then 1 else 0)
    rw [evalLiteral_eq_true_iff_polarity_eq]
    -- From h_addr_eq, extract idx equality and polarity equality
    have h_lit_bound : (lit.particle_idx : ℕ) < k := lit.particle_idx.isLt
    have h_i_bound : (i : ℕ) < k := i.isLt
    have h_idx_val : lit.particle_idx.val = i.val := by
      have h1 : (if lit.polarity = true then 1 else 0 : ℕ) ≤ 1 := by split <;> omega
      have h2 : (if (a.get i) = true then 1 else 0 : ℕ) ≤ 1 := by split <;> omega
      omega
    have h_idx : lit.particle_idx = i := Fin.ext h_idx_val
    subst h_idx
    -- Now h_addr_eq gives polarity match
    have h_pol_eq : (if lit.polarity = true then 1 else 0 : ℕ) =
        (if (a.get lit.particle_idx) = true then 1 else 0 : ℕ) := by omega
    cases h_pol : lit.polarity <;> cases h_val : (a.get lit.particle_idx) <;>
      simp_all

/--
**If a clause is satisfied by assignment a, then some literal in the clause
has its address in `literalAddressesFromAssignment a`.**
-/
theorem sat_implies_clause_has_selected_address {k : ℕ}
    (clause : Clause_EGPT k) (a : Vector Bool k)
    (h_sat : evalClause clause a = true) :
    ∃ lit ∈ clause, literalAddress lit ∈ literalAddressesFromAssignment a := by
  unfold evalClause at h_sat
  rw [List.any_eq_true] at h_sat
  rcases h_sat with ⟨lit, h_mem, h_eval⟩
  exact ⟨lit, h_mem, (evalLiteral_iff_mem_literalAddresses lit a).mp h_eval⟩

/--
**The NDM circuit: given an assignment's literal addresses and a CNF,
check if every clause contains at least one selected address.**

This operates entirely in address space — no direct reference to the
assignment vector, only to the addresses it selects.
-/
def ndmCircuitEval {k : ℕ} (cnf : SyntacticCNF_EGPT k) (a : Vector Bool k) : Bool :=
  cnf.all (fun clause => clause.any (fun lit =>
    decide (literalAddress lit ∈ literalAddressesFromAssignment a)))

/--
**The NDM circuit evaluation equals `evalCNF`.**

This is the capstone theorem: the NDM circuit IS evalCNF, operating
entirely in address space. The circuit checks whether the assignment's
selected addresses (k addresses from the 2k total) have nonempty
intersection with each clause's literal addresses.
-/
theorem ndmCircuitEval_eq_evalCNF {k : ℕ} (cnf : SyntacticCNF_EGPT k)
    (a : Vector Bool k) :
    ndmCircuitEval cnf a = evalCNF cnf a := by
  simp only [ndmCircuitEval, evalCNF, evalClause]
  congr 1
  ext clause
  congr 1
  ext lit
  -- Goal: decide (literalAddress lit ∈ literalAddressesFromAssignment a) = evalLiteral lit a
  cases h : evalLiteral lit a
  · -- evalLiteral lit a = false
    simp only [decide_eq_false_iff_not]
    intro h_mem
    have := (evalLiteral_iff_mem_literalAddresses lit a).mpr h_mem
    rw [h] at this
    exact absurd this Bool.noConfusion
  · -- evalLiteral lit a = true
    simp only [decide_eq_true_eq]
    exact (evalLiteral_iff_mem_literalAddresses lit a).mp h

/--
**The NDM circuit is memoryless: each clause check depends only on the
current clause and the fixed input addresses, not on previous clauses.**

This follows directly from the structure: `cnf.all` processes each clause
independently. The `decide (literalAddress lit ∈ literalAddressesFromAssignment a)`
check depends only on the clause's literals and the fixed address set `a`,
not on any state accumulated from previous clauses.
-/
theorem ndmCircuit_memoryless {k : ℕ}
    (a : Vector Bool k) (clause : Clause_EGPT k) :
    let clauseResult := clause.any (fun lit =>
      decide (literalAddress lit ∈ literalAddressesFromAssignment a))
    clauseResult = (clause.any (fun lit =>
      decide (literalAddress lit ∈ literalAddressesFromAssignment a))) := by
  rfl

/--
**The NDM circuit cost is polynomial: O(|cnf| × k).**

For each clause (|cnf| clauses), check each literal (≤ clause length ≤ k literals)
against the selected addresses. Total operations ≤ |cnf| × k.
-/
theorem ndmCircuit_cost_polynomial {k : ℕ} (cnf : SyntacticCNF_EGPT k)
    (h_clause_bound : ∀ c ∈ cnf, c.length ≤ k) :
    (cnf.map (fun c => c.length)).sum ≤ cnf.length * k := by
  apply sum_map_le_length_mul_bound
  exact h_clause_bound

/--
**Entropy bridge: NDM circuit evaluation matches the entropy walk determination.**

`ndmCircuitEval cnf a = true ↔ ndmEntropyWalk(composite).totalEntropy = 0`.
This chains through:
1. `ndmCircuitEval_eq_evalCNF`: circuit ↔ evalCNF
2. `ndmEntropyWalk_determines_sat`: entropy walk ↔ evalCNF
-/
theorem ndmCircuit_entropy_bridge {k : ℕ} (cnf : SyntacticCNF_EGPT k)
    (a : Vector Bool k) (h_clauses_nonempty : ∀ c ∈ cnf, c ≠ []) :
    ndmCircuitEval cnf a = true ↔
      (ndmEntropyWalk cnf (assignmentCompositePrime a)).totalEntropy = 0 := by
  rw [ndmCircuitEval_eq_evalCNF]
  exact (ndmEntropyWalk_determines_sat cnf a h_clauses_nonempty).symm

/--
**SAT ↔ ∃ assignment where the NDM circuit accepts.**

The existential form: the CNF is satisfiable iff there exists an
assignment whose selected addresses pass all clause checks.
-/
theorem ndmCircuit_sat_iff {k : ℕ} (cnf : SyntacticCNF_EGPT k) :
    (∃ a : Vector Bool k, ndmCircuitEval cnf a = true) ↔
      (∃ a : Vector Bool k, evalCNF cnf a = true) := by
  constructor
  · rintro ⟨a, h⟩
    exact ⟨a, (ndmCircuitEval_eq_evalCNF cnf a) ▸ h⟩
  · rintro ⟨a, h⟩
    exact ⟨a, (ndmCircuitEval_eq_evalCNF cnf a) ▸ h⟩

end EGPT.Complexity.UTM

-- EGPT — Electronic Graph Paper Theory
-- Copyright (C) 2026 Essam Abadir
-- Licensed under the DeSciX Community Source Code License (DCSL) v1.0.
-- See LICENSE and DeSciX_Community_License_v1.pdf in the repository root.
-- Provided WITHOUT ANY WARRANTY. See the DCSL for details.
